# gates.yaml
# Project-specific commands for the LLM quality gates.
# Replace the placeholder commands below with the actual commands for your stack.

# Command to run the entire test suite
test: "npm test -- --ci"

# Command to run the linter with auto-fix capabilities
lint: "npm run lint"

# Static type checking
type_check: "npx tsc --noEmit"

# Dependency vulnerability scan
security_scan: "npm audit"